# Generated by Django 3.0.1 on 2020-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paquete_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tip',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
