# Generated by Django 3.0.1 on 2020-01-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200130_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='usuarios',
            new_name='paquete',
        ),
    ]
