# Generated by Django 3.0.1 on 2020-01-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200128_1844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conceptos',
            new_name='Concepto',
        ),
    ]
