# Generated by Django 3.0.1 on 2020-01-31 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experiencia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='api.Paquete'),
        ),
        migrations.AlterField(
            model_name='video',
            name='paquete',
            field=models.ManyToManyField(related_name='videos', to='api.Paquete'),
        ),
    ]
