# Generated by Django 3.0.1 on 2020-02-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200131_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='foto',
            new_name='uri',
        ),
    ]
