# Generated by Django 3.0.1 on 2020-02-01 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200201_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
