# Generated by Django 3.0.1 on 2020-02-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_experiencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='aprobada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.ImageField(upload_to='')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Compra')),
            ],
        ),
    ]
