# Generated by Django 3.0.1 on 2020-02-08 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200203_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='uri',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_de_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
